# Setup
title:               DH
tagline:             'Words and Stuff'
description:         'Random notes'
url:                 https://dhsu.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate
  

# Custom vars
version:             0.0.1
#google_analytics_id: #UA-XXXX-Y
